### ISSUE TITLE
Zooming is out of control

### ISSUE THREAD

**Issue by jtiscione** [lewish/asciiflow#111] opened 2018-04-24 21:04 UTC
Is there a way to disable the zoom feature? I'm using a touch mouse and can hardly do anything without the screen zooming wildly in and out every couple seconds like a Powers of Ten video.
And unless I'm scrolled all the way in, the toolbar scrolls off the top of the window, so I have to keep zooming in and out just to get at the buttons.

**Comment by Qix-** [comment] 2019-02-11 18:51
> like a Powers of Ten video

I laughed, thanks

---

This is rather old so no worries if this is not really a concern for you anymore.

Here's a gif of me zooming first with a regular mouse, and then with my Macbook Pro touchpad. There _is_ a discrepancy in zooming speed.

Is this what you're talking about?

![kapture 2019-02-11 at 19 48 48](https://user-images.githubusercontent.com/885648/52585796-119b1a80-2e36-11e9-8e3c-3a9eb0d6becd.gif)

**Comment by Qix-** [comment] 2021-03-09 18:33
Duplicate of #28.

**Closed by Qix-** 2021-03-09 18:33 UTC
Labels: bug
