### ISSUE TITLE
Export not working

### ISSUE THREAD

**Issue by g-berthiaume** [lewish/asciiflow#252] opened 2022-10-18 19:50 UTC
What I draw
![image](https://user-images.githubusercontent.com/19377511/196529603-c41f7545-4c5f-42e9-a245-81d198673863.png)

What I export
![image](https://user-images.githubusercontent.com/19377511/196529708-298d4f25-1789-4714-b2db-612f52a7ac3b.png)

Link to reproduce [here](https://asciiflow.com/#/share/eJyrVspLzE1VssorzcnRUcpJrEwtUrJSqo5RqohRsrI0M9eJUaoEsowsTYCsktSKEiAnRkkBP3g0pefRlAYkNCEmJg%2Bbsj1EIgXvAnyqcZmOyp2C6qYZMTFFcJWETICrRZKdtkcbpK1Co0QT6he42XsUUkGiIAYOBxfhCKYiLAGjoFAKNI1ACClUAtUA3YNFdtoukIJziwkEONDejtVoloO0Nil4Z2JoxWcmRK4gJzGvhGAkT9sFD3pt9DCERwIO5%2BKOVG0sagk5BTMhPJq2SRdbYsJIDECF2pjJB9M8hCEEfIUjXWAkauJsgqCUCv2UEmyRmwJU04QnVEixDUcgQyRwZkDsAJ8tpAFMk4YQilGqVaoFAC6%2Bw1Q%3D)

Not sure what's going on. I'm not well verse in js.
Let me know if you have any questions.

**Comment by jmc5113** [comment] 2023-03-03 00:25
Yes I've been having this issue for a while as well. Seems there must not be much happening if its still broken. Are there any workarounds?

I've been pasting it into a text editor and fixing the lines. It seems like some kind of line wrap issue.

**Comment by kting28** [comment] 2023-06-07 02:41
Workaround is to delete the extra boxes created before import. See the fixed [version](https://asciiflow.com/#/share/eJyrVspLzE1VssorzcnRUcpJrEwtUrJSqo5RqohRsrI0t9SJUaoEsowsQayS1IoSICdGSQE%2FeDSl59GUBiS0JyYmD5uyPUQiBe8CfKpxmY7KnYLmJoQ6YvSjy2mDNFVolGhC%2FYFkbipIFMTA7hdsATQBW4AoKJQCTSIQMgqVQDVAt2CRnbYLpODcYgIBDbS3YzWa5SCtTQremRha8ZkJkSvIScwrIRi503bBA10bPfzgwY8n%2FNAicwbCIFSVhByCmQAeTdukS0wSmLZJG0fSQDENYQQ5KQK3G%2FDaA0EpFfopJdiiNQWopglPiJBiG44AhkhgiyWcAJ8dpAFMk4YQilGqVaoFANuhu1o%3D))

Use the pointer to select all items, identify the extra "white" spaces and delete them:

![image](https://github.com/lewish/asciiflow/assets/24449116/ff0f7a7a-2bcc-451d-a7ac-8b2018c91560)

**Comment by tristone13th** [comment] 2023-08-17 06:18
> 

This works, thanks!

**Comment by lewish** [comment] 2024-02-21 21:51
Duplicate of #185

**Closed by lewish** 2024-02-21 21:51 UTC
