### ISSUE TITLE
Export does not work

### ISSUE THREAD

**Issue by LowLevelMahn** [lewish/asciiflow#253] opened 2022-10-19 14:06 UTC
https://asciiflow.com/#/share/eJzNVEGOwjAM%2FErkMwdgu0L0iMSxP%2FCFQ2%2FdHhBIIITEI9A%2BBu1r%2BpItW1Y0TuzUKSqNrDa1sT3jSThBufnKIS33RTGBYnPMt5DCCeGAkC6T2QThWO%2Fmi6Te7fLDrv5AqK4%2F4zHEsn4azZKySPWY%2FNXfc%2FDOfNdX5anV%2BY7UtANmbvVE3MMEzB4S1DWaTFe6jkGuWjalne%2FOOXFKWPy3Qgq%2BaZp%2BWLK9VgEvVlaZmU%2BZj5iLfqPU5c7RqtqvlZE7KXVTcIio3I4PULO6Xvx2PzpMKCoFcUtw2UeDislwDyxS32TJ09uVOWsNOG1WiLlzjEPMuYj6HKkqCmr9x8M9mlHIXUz2adrffFUXj4aDZ%2FShbmb9%2BE2AhbXpysHzL8fUdhj3vyvNe22ciuMxOgFrXg1eFX1rCJYjupLKEM5w%2FgUG27Rh)

gives

![image](https://user-images.githubusercontent.com/580819/196714566-513f788c-1007-4398-89f1-f55eb5f39c30.png)

what is different to the editor view

![image](https://user-images.githubusercontent.com/580819/196714417-f078d265-528d-41e7-8d64-30b3041faaaf.png)

**Comment by IvanGordeyev** [comment] 2022-11-22 17:20
Duplicate of #252 Export not working
https://github.com/lewish/asciiflow/issues/252

I also wish this was fixed or if there was ability to replace a blank character with # or other

**Comment by lewish** [comment] 2024-02-21 21:51
Duplicate of #185

**Closed by lewish** 2024-02-21 21:51 UTC

**Comment by lewish** [comment] 2024-02-22 09:40
Not released yet, I'm doing a bit more testing, I'll close #185 when it's live!
