### ISSUE TITLE
Undesired hyphen conversion to '+' sign in text

### ISSUE THREAD

**Issue by jsamr** [lewish/asciiflow#86] opened 2017-03-30 14:20 UTC
First of all, thanks a lot for this great tool !
I'm using a lot asciiflow to document SCSS files, and often I label containers (squares) with their class names, which use `-` as in `o-my-object__element`. 
Could you offer the option to not auto-convert hyphens to plus sign when importing ?

**Comment by roundand** [comment] 2017-08-11 13:15
I also get "v" converted to "^" when I do an import, perhaps this should be part of the same issue?

**Comment by TimHandy** [comment] 2019-02-10 20:18
The hyphen and the 'v' import issues are the only things that I've noticed that are preventing me using this for our team at work. Other than this it's a brilliant app, and far better for documentation than Visio for our needs. Looks like development might be dead however?

I'm trying to create network diagrams but every time I want to edit the diagram by importing, my server names eg. 'VM-DC01' get converted to 'VM+DC01' and any time the word 'server' or any letter 'v' appears, it gets converted to 'ser^er'.

**Comment by Qix-** [comment] 2019-02-11 18:01
@roundand That was fixed in #109.

@jsamr I know this is a _really_ old issue but could you provide an example?

**Comment by TimHandy** [comment] 2019-02-11 18:32
Example of hyphen in text being converted to a '+' :
```
+---------------+
| TLA-EX01 (VM) |
| 192.168.0.2   |
|               |
|               |
|               |
+---------------+
```
Becomes like the following after import:
```
+---------------+
| TLA+EX01 (VM) |
| 192.168.0.2   |
|               |
|               |
|               |
+---------------+
```

Thanks for fixing the other 'v' import issue!

**Comment by Qix-** [comment] 2019-02-11 18:38
Reproduced, thanks for the test case :)

**Comment by lewish** [comment] 2021-03-06 11:55
With the move to box drawing characters, this issue is now fixed/avoided - please let me know if you have feedback!

**Closed by lewish** 2021-03-06 11:55 UTC
Labels: bug
