### ISSUE TITLE
[Bug] Copy/Paste not working in FireFox

### ISSUE THREAD

**Issue by cruscio** [lewish/asciiflow#174] opened 2021-03-05 13:39 UTC
Firefox: Draw a square. Select it. Ctrl-C / Ctrl-V - and the text that was previously in the clipboard is pasted, not the square. 
Same action worked fine after switching to Chrome.

Firefox 86.0 (64-bit) on Windows 10

**Comment by Qix-** [comment] 2021-03-05 14:22
Please search a bit next time :)

Duplicate of #172.

**Closed by Qix-** 2021-03-05 14:22 UTC

**Comment by cruscio** [comment] 2021-03-05 15:57
@Qix- I [did](https://github.com/lewish/asciiflow/search?q=firefox&type=issues) - there were 6 results, none of them seemed related. I wasn't able to reproduce the issue in another browser, so I figured searching for FF was adequate. Apologies for the trouble.
