### ISSUE TITLE
Bug in export

### ISSUE THREAD

**Issue by deostroll** [lewish/asciiflow#275] opened 2023-10-13 08:26 UTC
I guess this is self-explanatory through the below three screenshots.

Fig1: This is the view from the website of interim work
![image](https://github.com/lewish/asciiflow/assets/415336/164e7cdf-f100-4883-8f1f-96f809c2885c)

Fig2: View in notepad++ (zoomed out)
![image](https://github.com/lewish/asciiflow/assets/415336/2c6f9535-e73c-463d-a180-5a51cfdec6ae)

Fig3: When I actually checked the exported text on the website
![image](https://github.com/lewish/asciiflow/assets/415336/362f2fb7-ae99-4e6f-917b-819af1aaee5e)

**Comment by lewish** [comment] 2024-02-21 21:51
Duplicate of #185

**Closed by lewish** 2024-02-21 21:51 UTC
